export const GET_STARTED_BUTTON_HEIGHT = 56;
export const GET_STARTED_BUTTON_FONT_SIZE = 13;
export const GET_STARTED_BUTTON_TRACKING_EM = 0.22;
export const GET_STARTED_BUTTON_BACKGROUND = "#D4C4AB";
export const GET_STARTED_BUTTON_TEXT = "#1A1816";
